export * from './oficina/cliente.type'
export * from './oficina/mecanico.type'
export * from './oficina/fornecedor.type'
export * from './oficina/peca.type'
export * from './oficina/ordem-servico.type'
